version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    groups:
      docker-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
